version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.4
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development